#!/usr/bin/env python
from flask import Flask, request
from flask_cors import cross_origin
import fasttext, re, json, os, numpy as np, click
from gunicorn.app.base import BaseApplication

class cFlask(Flask) :
    def __init__(self, model, *args) :
        super(cFlask, self).__init__(__name__, *args)
        config = json.load(open(os.path.join(model, 'model.conf'), 'rt'))
        self.config.update(config)
        self.parser = self.init_parser(model)
    def init_parser(self, model) :
        self.level_models = [fasttext.load_model(os.path.join(model, fname)) for fname in self.config['models']]
    def tokenize(self, sent, lower=True) :
        if lower :
            return [w for w in re.split(r"[^a-zA-Z]+", sent.lower()) if len(w) > 1]
        else :
            return [w for w in re.split(r"[^a-zA-Z]+", sent) if len(w) > 1]
    def query(self, qry) :
        tokens = self.tokenize(qry)
        res = []
        for m in self.level_models :
            r = m.predict(' '.join(tokens), k = -1)
            res.append(dict(zip(r[0], r[1].tolist())))
        paths = []
        for cat in self.config['combined_category'] :
            path = np.array([r.get(k, 0.) for k, r in zip(cat, res)])
            prob = path.prod()**(1/len(path))
            p = dict(zip(self.config['levels'], zip(cat, path)))
            p['Pr'] = prob
            paths.append(p)
        if not self.config['multi_label'] :
            Pr_total = sum([ p['Pr'] for p in paths ])
            for p in paths :
                p['Pr'] /= Pr_total
        else :
            paths = [p for p in paths if p['Pr'] >= 0.5]
        return sorted(paths, key=lambda x:-x['Pr'])


@app.route("/query", methods=['GET', 'POST'])
@cross_origin(allow_headers=['Content-Type'])
def query() :
    qry = request.form.get('q', '') if request.method == 'POST' else request.args.get('q', '')
    paths = app.query(qry)
    return json.dumps(paths)

@app.route("/batch_query", methods=['GET', 'POST'])
@cross_origin(allow_headers=['Content-Type'])
def batch_query() :
    result = {}
    qry = request.form.get('q', '') if request.method == 'POST' else request.args.get('q', '')
    for q in qry.split('\n') :
        res = app.query(q)
        result[q] = res
    return json.dumps(result)


class Application(BaseApplication) :
    def __init__(self, app, options={}):
        self.options = options
        self.application = app
        super().__init__()
    def load_config(self):
        config = { k: v for k, v in self.options.items() \
                   if k in self.cfg.settings and value is not None }
        for k, v in config.items() :
            self.cfg.set(key.lower(), value)
    def load(self):
        return self.application

@click.command()
@click.options('-m', '--model', help='folder for the model generated by fastSrc_build', required=True)
@click.options('-w', '--workers', help='number of workers (processors) to be used. DEFAULT: 1', default=1)
@click.options('-b', '--bind', help='IP and port to be used for the API. DEFAULT: 0.0.0.0:4125', default='0.0.0.0:4125')
def main(model, workers, bind) :
    app = cFlask(model)
    app.query('homo sapien')
    Application(app, dict(bind=bind, workers=workers)).run()

if __name__ == '__main__' :
    main()
